#!/bin/bash
INPUT_FILE_DIR=$1

/home/daniels/tools/affyPowerTools/apt_2.11.4_linux_64_bit_x86_binaries/bin/apt-probeset-genotype \
	-c /home/pgccnv/somaticcnv_daniels/resources/affy/apt_files/GenomeWideSNP_6.cdf \
	--special-snps /home/pgccnv/somaticcnv_daniels/resources/affy/apt_files/GenomeWideSNP_6.specialSNPs \
	-o apt_output \
	-a birdseed-v2 \
	--read-models-birdseed /home/pgccnv/somaticcnv_daniels/resources/affy/apt_files/GenomeWideSNP_6.birdseed-v2.models \
	--write-prior \
	--write-models \
	--write-profile \
	--summaries \
	"$INPUT_FILE_DIR"/*.cel

bcftools +affy2vcf \
	--csv /home/pgccnv/somaticcnv_daniels/resources/affy/GenomeWideSNP_6.na35.annot.csv \
	--fasta-ref /home/pgccnv/somaticcnv_daniels/resources/hg19/hg19.fa \
	--calls apt_output/birdseed-v2.calls.txt \
	--confidences apt_output/birdseed-v2.confidences.txt \
	--summary apt_output/birdseed-v2.summary.txt \
	--snp apt_output/birdseed-v2.snp-models.txt \
	--output apt_output/affy_hg19.vcf.gz \
	-Oz

#gzip apt_output/affy_hg19.vcf

liftCoordinates \
	-swapAlleleAB \
	-faFile /home/pgccnv/somaticcnv_daniels/resources/hg38/hg38.fa \
	/home/pgccnv/somaticcnv_daniels/resources/chains/hg19ToHg38.over.chain.gz \
	apt_output/affy_hg19.vcf.gz \
	apt_output/affy_hg38.vcf.gz \
	apt_output/liftover.log

if [ $? -eq 0 ]; then
	origLines=$(wc -l apt_output/affy_hg19.vcf)
	liftLines=$(zcat apt_output/affy_hg38.vcf.gz | wc -l)
	echo "Before liftover: $origLines records"
	echo "After  liftover: $liftLines records"
	rm apt_output/affy_hg19.vcf.gz
else
	exit 1
fi

~/bin/bcftools sort -Oz -o apt_output/tmp.vcf.gz  apt_output/affy_hg38.vcf.gz
mv apt_output/tmp.vcf.gz apt_output/affy_hg38.vcf.gz
bcftools index apt_output/affy_hg38.vcf.gz
